### PR TITLE
Added PartitionAt, supporting types, and tests

### PR DESCRIPTION
**Pull request by awcullen**
First try...

### CODE REVIEW

**Comment by awcullen** [comment]
I see that Partition also allows you pass in a slice of Buffers with the result being one big logical buffer. The wrinkle is that the passed in buffers may be of varying lengths. In this case I believe WriteAt  should not be able to lengthen any buffer except for the last.  Let me fix this case and add a test.

**Comment by djherbis** [comment]
Hey, I'll review this when I get chance, but is there a reason you chose to continue down this route vs. just using something like io.MultiReader etc. mentioned in #7.

**Comment by djherbis** [comment]
First few comments:
- Don't commit debug.test
- Instead of adding the *At versions into the existing files, can we copy the existing files, add _at to them (except the test file), it'll make it easier for me to diff the files (I'm expecting the diff to basically just be in types except for ReadAt/WriteAt, and tests)
- Please reference the issue in the commit message #7 
- In your tests, please make sure you include the checkCap, runPerfectSeries tests as well

**Comment by janekolszak** [comment]
Hi,
Are you planning to merge?
Thanks

**Comment by djherbis** [comment]
Hey @janekolszak I'm editing the PR now, I've made some progress applying the changes I originally requested.

Once I've finished tidying it up I'll merge it.

**Comment by janekolszak** [comment]
Do you need any help?

**Comment by djherbis** [comment]
Sorry I was close to done but I went on vacation for a long weekend. Might
have some time Monday

**Comment by djherbis** [comment]
@janekolszak Merged it in, along with my changes and tests

**Comment by janekolszak** [comment]
Thank you so much! :)

**Pull request merged**
